ProjectManagement/Controllers/ProjectBidController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectManagement.Data;
using ProjectManagement.DataContextModels;
using ProjectManagement.Utilities;

namespace ProjectManagement.Controllers
{
    [Authorize(Roles = "Student")]
    public class ProjectBidController : BaseController
    {
        private readonly ApplicationDbContext _context;

        public ProjectBidController(ApplicationDbContext context, UserManager<ApplicationUser> userManager) : base(userManager)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetProjects(int? page, int? limit, string sortBy, string direction, string projectName = null, string projectType = null, 
            string projectSubType = null, string Professor = null)
        {
            int total;
            var records = GetJsonData(page, limit, sortBy, direction, out total, projectName, projectType, projectSubType, Professor);

            var result = Json(new { records, total });

            return result;
        }

        public List<Project> GetJsonData(int? page, int? limit, string sortBy, string direction, out int total, string projectName = null, string projectType = null, 
            string projectSubType = null, string Professor = null)
        {
            var isBac = _context.ApplicationUsers.Where(p => p.Id == UserIdentity.Id).Select(p => p.IsBachelorStudent).SingleOrDefault();
            var records = _context.Projects.Include(p => p.Creator).Include(p => p.Updater)
                .Select(p => new Project()
                {
                    Id = p.Id,
                    Name = p.Name,
                    IsApproved = p.IsApproved,
                    IsClosed = p.IsClosed,
                    ApprovalSummary = p.IsApproved.Value ? "Yes" : "No",
                    CloserSummary = p.IsClosed?"Yes":"No",
                    MaxApprovedStudents = p.MaxApprovedStudents,
                    ProjectType = p.ProjectType,
                    ProjectSubType = p.ProjectSubType,
                    CreatedBy = (string.IsNullOrEmpty(p.Creator.FirstName) || string.IsNullOrEmpty(p.Creator.LastName)) ? p.Creator.UserName : (p.Creator.FirstName + " " + p.Creator.LastName)
                }).Where(p => p.IsApproved.Value && !p.IsClosed && !_context.ProjectStudents.Select(c => c.ApplicationUserId).Contains(UserIdentity.Id) && isBac==true)
                .AsQueryable();

            
            if (!string.IsNullOrEmpty(projectName))
            {
                records = records.Where(r => r.Name.ToLower().Contains(projectName.Trim().ToLower()));
            }
            if (!string.IsNullOrEmpty(projectType) && projectType != "Select")
            {
                records = records.Where(r => r.ProjectType.ToLower().Contains(projectType.Trim().ToLower()));
            }
            if (!string.IsNullOrEmpty(projectSubType) && projectSubType != "Select")
            {
                records = records.Where(r => r.ProjectSubType.ToLower().Contains(projectSubType.Trim().ToLower()));
            }
            if (!string.IsNullOrEmpty(Professor))
            {
                records = records.Where(r => r.CreatedBy.ToLower().Contains(Professor.Trim().ToLower()));
            }

           
            total = records.Count();

            if (!string.IsNullOrEmpty(sortBy) && !string.IsNullOrEmpty(direction))
            {
                if (direction.Trim().ToLower() == "asc")
                {
                    records = SortHelper.OrderBy(records, sortBy);
                }
                else
                {
                    records = SortHelper.OrderByDescending(records, sortBy);
                }
            }
            if (page.HasValue && limit.HasValue)
            {
                int start = (page.Value - 1) * limit.Value;
                records = records.Skip(start).Take(limit.Value);
            }

           
            return records.ToList();
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }

            var isApplied = await _context.ProjectStudentChoices.FirstOrDefaultAsync(p => p.ProjectId == id && p.ApplicationUserId == UserIdentity.Id);
            ViewBag.IsApplied = isApplied;
            return View(project);
        }

        public IActionResult MyProjects()
        {
            ViewBag.StudentId = UserIdentity.Id;
            return View();
        }

    }
}

ProjectManagement/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using FastMember;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using ProjectManagement.Data;
using ProjectManagement.DataContextModels;
using ProjectManagement.Utilities;

namespace ProjectManagement.Controllers
{
    [Authorize(Roles = "SystemAdmin,Supervisor")]
    public class ProjectsController : BaseController
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IEmailService _emailService;

   
        public ProjectsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager,
            IEmailService emailService) : base(userManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
            _emailService = emailService;
        }



        // GET: Projects
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult NotFound()
        {
            return View();
        }
        [HttpGet]
        public ActionResult GetProjects(int? page, int? limit, string sortBy, string direction, string projectName = null, string projectType = null, bool? isApproved = null, bool? isClosed = null)
        {
            int total;
            var records = GetJsonData(page, limit, sortBy, direction, out total, projectName, projectType, isApproved, isClosed);

            var result = Json(new { records, total });

            return result;
        }

        public List<Project> GetJsonData(int? page, int? limit, string sortBy, string direction, out int total, string projectName = null, string projectType = null, bool? isApproved = null, bool? isClosed = null)
        {

            var records = _context.Projects.Include(p => p.Creator).Include(p => p.Updater)
                .Select(p => new Project()
                {
                    Id = p.Id,
                    Name = p.Name,
                    IsApproved = p.IsApproved,
                    IsClosed = p.IsClosed,
                    ApprovalSummary = p.IsApproved.Value ? "Yes" : "No",
                    CloserSummary = p.IsClosed ? "Yes" : "No",
                    MaxApprovedStudents = p.MaxApprovedStudents,
                    ProjectType = p.ProjectType,
                    CreatedBy = (string.IsNullOrEmpty(p.Creator.FirstName) || string.IsNullOrEmpty(p.Creator.LastName)) ? p.Creator.UserName : (p.Creator.FirstName + " " + p.Creator.LastName)
                })
                .AsQueryable();


            if (!string.IsNullOrEmpty(projectName))
            {
                records = records.Where(r => r.Name.ToLower().Contains(projectName.Trim().ToLower()));
            }
            if (!string.IsNullOrEmpty(projectType) && projectType != "Select")
            {
                records = records.Where(r => r.ProjectType.ToLower().Contains(projectType.Trim().ToLower()));
            }

            if (isApproved != null)
            {
                records = records.Where(r => r.IsApproved == isApproved);
            }
            if (isClosed != null)
            {
                records = records.Where(r => r.IsClosed == isClosed);
            }
            total = records.Count();

            if (!string.IsNullOrEmpty(sortBy) && !string.IsNullOrEmpty(direction))
            {
                if (direction.Trim().ToLower() == "asc")
                {
                    records = SortHelper.OrderBy(records, sortBy);
                }
                else
                {
                    records = SortHelper.OrderByDescending(records, sortBy);
                }
            }
            if (page.HasValue && limit.HasValue)
            {
                int start = (page.Value - 1) * limit.Value;
                records = records.Skip(start).Take(limit.Value);
            }

            return records.ToList();
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // GET: Projects/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,ProjectTools,ProjectType,ProjectSubType,MaxApprovedStudents")] Project project)
        {
            if (ModelState.IsValid)
            {
                project.CreatedBy = UserIdentity.Id;
                project.CreatedOn = DateTime.Now;
                if (project.ProjectType != "Bachelor")
                {
                    project.ProjectSubType = string.Empty;
                }
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (User.IsInRole("SystemAdmin"))
            { 
                var allProject = await _context.Projects.FindAsync(id);
                if (allProject == null)
                {
                    return RedirectToAction(nameof(Index));
                }
                return View(allProject);

            }
            var project = await _context.Projects.Where(p => p.Creator.Id == UserIdentity.Id &&p.Id==id).SingleOrDefaultAsync();
            if (project == null)
            {
                return RedirectToAction(nameof(NotFound));
            }
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,ProjectTools,ProjectType,ProjectSubType,MaxApprovedStudents,CreatedBy,CreatedOn")] Project project)
        {
            if (id != project.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    project.UpdatedBy = UserIdentity.Id;
                    project.UpdatedOn = DateTime.Now;
                    if (project.ProjectType != "Bachelor")
                    {
                        project.ProjectSubType = string.Empty;
                    }
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // POST: ProjectStudents/Delete/5
        [HttpPost, ActionName("UnAllocateProject")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UnAllocateProject(int id)
        {
            var projectStudent =  _context.ProjectStudents.Where(p=>p.ProjectId==id);
            _context.ProjectStudents.RemoveRange(projectStudent);

            
          var projectEdit=new Project(){Id = id};
          projectEdit.IsClosed = false;
      
          _context.Entry(projectEdit).Property("IsClosed").IsModified = true;

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

       

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> Confirmed(int id)
        {
            if (User.IsInRole("SystemAdmin"))
            {
                var projects = await _context.Projects
                    .Include(p => p.ProjectStudentChoices)
                    .Include(p => p.ProjectStudents)
                    .FirstOrDefaultAsync(p => p.Id == id);
              
                if (projects.ProjectStudents.Any())
                {
                    return Json("Warning: project have exist students approved.");
                }
                else if (projects.ProjectStudentChoices.Any())
                {
                    return Json("Warning: project has applied students in the queue.");
                }

                _context.Projects.Remove(projects);
                await _context.SaveChangesAsync();
                return Json("Success: Project is removed successfully.");

            }
            var project = await _context.Projects
                .Include(p => p.ProjectStudentChoices)

ProjectManagement/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ProjectManagement.DataContextModels.ApplicationUser> _UserManager
@inject SignInManager<ProjectManagement.DataContextModels.ApplicationUser> _SignInManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PMO</title>
    <script src="~/js/jquery-2.1.3.min.js"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/grid-0.4.3.min.js"></script>
 
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/lib/bootstrap/dist/css/grid-0.4.3.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />

        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/lib/bootstrap/dist/css/grid-0.4.3.css" rel="stylesheet" />

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />

        <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />

        <link rel="stylesheet"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
              crossorigin="anonymous"
              href="https://sstackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position"
              asp-fallback-test-value="absolute"
              asp-suppress-fallback-integrity="true" />


    <script type="text/javascript">
        function DisplaySuccessMessage(message) {
            $('#divSuccess').text(message);
            $('#successModal').modal('show');
        }
        function DisplayWarningMessage(message) {
            $('#divWarning').text(message);
            $('#warningModal').modal('show');
        }
        function DisplayErrorMessage(message) {
            if (message == '') {
                $('#errorModal').modal('show');
            }
            else {
                $('#divError').text(message);
                $('#errorModal').modal('show');
            }

        }

    </script>
   
</head>
<body>
   <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            @if (_SignInManager.IsSignedIn(User))
            {
                if (User.IsInRole("SystemAdmin") || User.IsInRole("Supervisor"))
                {
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a asp-area="" asp-controller="Projects" asp-action="Index" class="navbar-brand" style="color: aliceblue;">Our Project Platform</a>
                    </div>
                }
                else if (User.IsInRole("Student"))
                {
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a asp-area="" asp-controller="ProjectBid" asp-action="Index" class="navbar-brand" style="color: aliceblue;">Our Project Platform</a>
                    </div>



                }
                else
                {
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand" style="color: aliceblue;">Our Project Platform</a>
                    </div>
                }
            }
            else
            {
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand" style="color: aliceblue;">Our Project Platform</a>
                    </div>
                    }

                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            @if (_SignInManager.IsSignedIn(User))
                            {
                                if (User.IsInRole("SystemAdmin"))
                                {
                                    <li><a asp-area="" asp-controller="Projects" asp-action="Index" style="color: aliceblue;">Projects</a></li>
                                    <li><a asp-area="" asp-controller="Projects" asp-action="ManageUsers" style="color: aliceblue;">Users</a></li>
                                    <li><a asp-area="" asp-controller="Projects" asp-action="NotAllocatedStudents" style="color: aliceblue;">Students without choices</a></li>
                                    <li><a asp-area="" asp-controller="Projects" asp-action="Reports" style="color: aliceblue;">Reports</a></li>
                                    <li><a asp-area="" asp-controller="Projects" asp-action="StudentsAverage" style="color: aliceblue;">Students Average</a></li>

                                }
                                else if (User.IsInRole("Supervisor"))
                                {
                                    <li><a asp-area="" asp-controller="Projects" asp-action="Index" style="color: aliceblue;">Projects</a></li>


                                }
                                else if (User.IsInRole("Student"))
                                {


                                    <li><a asp-area="" asp-controller="ProjectBid" asp-action="Index" style="color: aliceblue;">Available Projects</a></li>
                                    <li><a asp-area="" asp-controller="ProjectBid" asp-action="MyProjects" style="color: aliceblue;">My Projects</a></li>

                                }
                                else
                                {

                        <label style="margin-top: 15px; color: Red;" dir="rtl">Please, wait to get Admin permission, then click on your username (your email) to fill your profile details.</label>
                                }
                            }
                        </ul>
                        <partial name="_LoginPartial" />
                    </div>
                </div>

</nav>
<div><br/></div>
    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        <div id="errorModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Error</h4>
                    </div>
                    <div class="modal-body">
                        <div class="alert alert-danger" id="divError">
                            Sorry, An error has occured while processing your request
                        </div>
                    </div>

                </div>

            </div>
        </div>
        <div id="warningModal" class="modal fade" role="dialog" style="z-index: 9998">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Warning</h4>
                    </div>
                    <div class="modal-body">
                        <div class="alert alert-warning" id="divWarning">
                            Sorry, An error has occured while processing your request
                        </div>
                    </div>

                </div>

            </div>
        </div>
        <div id="successModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Success</h4>
                    </div>
                    <div class="modal-body">
                        <div class="alert alert-success" id="divSuccess">
                            Sorry, An error has occured while processing your request
                        </div>
                    </div>

                </div>

            </div>
        </div>

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - PMO @*<br /> <strong>Implemented By:</strong> Saif Amer*@</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/grid-0.4.3.js" asp-append-version="true"></script>
        <script src="~/js/jquery-2.1.3.min.js"></script>
        <script src="~/js/grid-0.4.3.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/js/grid-0.4.3.js" asp-append-version="true"></script>
        <script src="~/js/jquery-2.1.3.min.js"></script>
        <script src="~/js/grid-0.4.3.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)

</body>
</html>