ProjectManagement/Controllers/ProjectBidController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectManagement.Data;
using ProjectManagement.DataContextModels;
using ProjectManagement.Utilities;

namespace ProjectManagement.Controllers
{
    [Authorize(Roles = "Student")]
    public class ProjectBidController : BaseController
    {
        private readonly ApplicationDbContext _context;

        public ProjectBidController(ApplicationDbContext context, UserManager<ApplicationUser> userManager) : base(userManager)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetProjects(int? page, int? limit, string sortBy, string direction, string projectName = null, string projectType = null, 
            string projectSubType = null, string Professor = null)
        {
            int total;
            var records = GetJsonData(page, limit, sortBy, direction, out total, projectName, projectType, projectSubType, Professor);

            var result = Json(new { records, total });

            return result;
        }

        public List<Project> GetJsonData(int? page, int? limit, string sortBy, string direction, out int total, string projectName = null, string projectType = null, 
            string projectSubType = null, string Professor = null)
        {
            var isBac = _context.ApplicationUsers.Where(p => p.Id == UserIdentity.Id).Select(p => p.IsBachelorStudent).SingleOrDefault();
            var records = _context.Projects.Include(p => p.Creator).Include(p => p.Updater)
                .Select(p => new Project()
                {
                    Id = p.Id,
                    Name = p.Name,
                    IsApproved = p.IsApproved,
                    IsClosed = p.IsClosed,
                    ApprovalSummary = p.IsApproved.Value ? "Yes" : "No",
                    CloserSummary = p.IsClosed?"Yes":"No",
                    MaxApprovedStudents = p.MaxApprovedStudents,
                    ProjectType = p.ProjectType,
                    ProjectSubType = p.ProjectSubType,
                    CreatedBy = (string.IsNullOrEmpty(p.Creator.FirstName) || string.IsNullOrEmpty(p.Creator.LastName)) ? p.Creator.UserName : (p.Creator.FirstName + " " + p.Creator.LastName)
                }).Where(p => p.IsApproved.Value && !p.IsClosed && !_context.ProjectStudents.Select(c => c.ApplicationUserId).Contains(UserIdentity.Id) && isBac==true)
                .AsQueryable();

            
            if (!string.IsNullOrEmpty(projectName))
            {
                records = records.Where(r => r.Name.ToLower().Contains(projectName.Trim().ToLower()));
            }
            if (!string.IsNullOrEmpty(projectType) && projectType != "Select")
            {
                records = records.Where(r => r.ProjectType.ToLower().Contains(projectType.Trim().ToLower()));
            }
            if (!string.IsNullOrEmpty(projectSubType) && projectSubType != "Select")
            {
                records = records.Where(r => r.ProjectSubType.ToLower().Contains(projectSubType.Trim().ToLower()));
            }
            if (!string.IsNullOrEmpty(Professor))
            {
                records = records.Where(r => r.CreatedBy.ToLower().Contains(Professor.Trim().ToLower()));
            }

           
            total = records.Count();

            if (!string.IsNullOrEmpty(sortBy) && !string.IsNullOrEmpty(direction))
            {
                if (direction.Trim().ToLower() == "asc")
                {
                    records = SortHelper.OrderBy(records, sortBy);
                }
                else
                {
                    records = SortHelper.OrderByDescending(records, sortBy);
                }
            }
            if (page.HasValue && limit.HasValue)
            {
                int start = (page.Value - 1) * limit.Value;
                records = records.Skip(start).Take(limit.Value);
            }

           
            return records.ToList();
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }

            var isApplied = await _context.ProjectStudentChoices.FirstOrDefaultAsync(p => p.ProjectId == id && p.ApplicationUserId == UserIdentity.Id);
            ViewBag.IsApplied = isApplied;
            return View(project);
        }

        public IActionResult MyProjects()
        {
            ViewBag.StudentId = UserIdentity.Id;
            return View();
        }

    }
}

ProjectManagement/Controllers/ProjectStudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectManagement.Data;
using ProjectManagement.DataContextModels;
using ProjectManagement.Utilities;

namespace ProjectManagement.Controllers
{
    [Authorize(Roles = "SystemAdmin,Student")]
    public class ProjectStudentsController : BaseController
    {
        private readonly ApplicationDbContext _context;

        public ProjectStudentsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager) : base(userManager)
        {
            _context = context;
        }

        [HttpGet]
        public ActionResult GetProjects(int? page, int? limit, string sortBy, string direction, int projectId, string studentId)
        {
            int total;
            var records = GetJsonData(page, limit, sortBy, direction, out total, projectId, studentId);

            var result = Json(new { records, total });

            return result;
        }

        public List<ProjectStudent> GetJsonData(int? page, int? limit, string sortBy, string direction, out int total, int projectId, string studentId)
        {
            var records = _context.ProjectStudents
                .Include(p => p.Project)
                .Include(p => p.ApplicationUser)
                .Include(p => p.Creator)
                .Include(p => p.Updater)
                .Select(p => new ProjectStudent()
                {
                    Id = p.Id,
                    CreatedOn = p.CreatedOn,
                    ProjectName = p.Project.Name,
                    StudentName = (string.IsNullOrEmpty(p.ApplicationUser.FirstName) || string.IsNullOrEmpty(p.ApplicationUser.LastName)) ? p.ApplicationUser.UserName
                    : (p.ApplicationUser.FirstName + " " + p.ApplicationUser.LastName),
                    ApplicationUserId = p.ApplicationUserId,
                    Professor = (string.IsNullOrEmpty(p.Project.Creator.FirstName) || string.IsNullOrEmpty(p.Project.Creator.LastName)) ? p.Project.Creator.UserName
                    : (p.Project.Creator.FirstName + " " + p.Project.Creator.LastName),
                    ProjectId = p.ProjectId
                })
                .AsQueryable();

            if (projectId != 0)
            {
                records = records.Where(r => r.ProjectId == projectId);
            }

            if (!string.IsNullOrEmpty(studentId))
            {
                records = records.Where(r => r.ApplicationUserId == studentId);
            }

            total = records.Count();

            if (!string.IsNullOrEmpty(sortBy) && !string.IsNullOrEmpty(direction))
            {
                if (direction.Trim().ToLower() == "asc")
                {
                    records = SortHelper.OrderBy(records, sortBy);
                }
                else
                {
                    records = SortHelper.OrderByDescending(records, sortBy);
                }
            }
            if (page.HasValue && limit.HasValue)
            {
                int start = (page.Value - 1) * limit.Value;
                records = records.Skip(start).Take(limit.Value);
            }

            return records.ToList();
        }

        // GET: ProjectStudents
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.ProjectStudents.Include(p => p.ApplicationUser).Include(p => p.Creator).Include(p => p.Project).Include(p => p.Updater);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: ProjectStudents/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectStudent = await _context.ProjectStudents
                .Include(p => p.ApplicationUser)
                .Include(p => p.Creator)
                .Include(p => p.Project)
                .Include(p => p.Updater)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (projectStudent == null)
            {
                return NotFound();
            }

            return View(projectStudent);
        }

        // GET: ProjectStudents/Create
        public IActionResult Create()
        {
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["CreatedBy"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Description");
            ViewData["UpdatedBy"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: ProjectStudents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ProjectId,ApplicationUserId,CreatedBy,CreatedOn,UpdatedBy,UpdatedOn")] ProjectStudent projectStudent)
        {
            if (ModelState.IsValid)
            {
                _context.Add(projectStudent);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id", projectStudent.ApplicationUserId);
            ViewData["CreatedBy"] = new SelectList(_context.Users, "Id", "Id", projectStudent.CreatedBy);
            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Description", projectStudent.ProjectId);
            ViewData["UpdatedBy"] = new SelectList(_context.Users, "Id", "Id", projectStudent.UpdatedBy);
            return View(projectStudent);
        }

        // GET: ProjectStudents/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectStudent = await _context.ProjectStudents.FindAsync(id);
            if (projectStudent == null)
            {
                return NotFound();
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id", projectStudent.ApplicationUserId);
            ViewData["CreatedBy"] = new SelectList(_context.Users, "Id", "Id", projectStudent.CreatedBy);
            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Description", projectStudent.ProjectId);
            ViewData["UpdatedBy"] = new SelectList(_context.Users, "Id", "Id", projectStudent.UpdatedBy);
            return View(projectStudent);
        }

        // POST: ProjectStudents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProjectId,ApplicationUserId,CreatedBy,CreatedOn,UpdatedBy,UpdatedOn")] ProjectStudent projectStudent)
        {
            if (id != projectStudent.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(projectStudent);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectStudentExists(projectStudent.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id", projectStudent.ApplicationUserId);
            ViewData["CreatedBy"] = new SelectList(_context.Users, "Id", "Id", projectStudent.CreatedBy);
            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Description", projectStudent.ProjectId);
            ViewData["UpdatedBy"] = new SelectList(_context.Users, "Id", "Id", projectStudent.UpdatedBy);
            return View(projectStudent);
        }

        // GET: ProjectStudents/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectStudent = await _context.ProjectStudents
                .Include(p => p.ApplicationUser)
                .Include(p => p.Creator)
                .Include(p => p.Project)
                .Include(p => p.Updater)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (projectStudent == null)
            {
                return NotFound();
            }

            return View(projectStudent);
        }

        // POST: ProjectStudents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var projectStudent = await _context.ProjectStudents.FindAsync(id);
            _context.ProjectStudents.Remove(projectStudent);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectStudentExists(int id)
        {
            return _context.ProjectStudents.Any(e => e.Id == id);
        }
    }
}

ProjectManagement/Views/ProjectBid/Details.cshtml
@model ProjectManagement.DataContextModels.Project
@inject ProjectManagement.Data.ApplicationDbContext _Context ;


@{
    ViewData["Title"] = "Details";
}
<script type="text/javascript">
    var gridStudentChoices;
    $(document).ready(function () {

         // Load Grid using json object
        gridStudentChoices = $("#gridStudentChoices").grid({
            dataKey: "id",
            uiLibrary: "bootstrap",
            columns: [
                { field: "studentName", title: "Student Name", sortable: true, width: 40 },
                { field: "createdOn", title: "Selection Date", sortable: true, width: 40 ,formatter:'date', formatoptions:{srcformat:"Y-m-d",newformat:"d/m/Y"}},

            ],
            pager: { enable: true, limit: 40, sizes: [2, 5, 10, 20, 40] }
        });



    });



    function Apply(id) {
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Create", "ProjectStudentChoices")',
            data: { 'projectId': id },
            success: function (data) {
                DisplaySuccessMessage('Applied successfully');
                $("#btnApply").attr("disabled", true);
                location.reload();
            },
            error: function (data) {
                DisplayErrorMessage('');
            }
        });
    }

      function Retreat(id) {
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Retreat", "ProjectStudentChoices")',
            data: { 'id': id },
            success: function (data) {
                DisplaySuccessMessage('Done');

                location.reload();
            },
            error: function (data) {
                DisplayErrorMessage('');
            }
        });
    }


</script>
<h2>Details</h2>
<div class="panel panel-default">
    <div class="panel-heading">
        Project Info
        @{
            var selectProject = _Context.ProjectStudents.Where(p => p.ProjectId == Model.Id).FirstOrDefault(c=>c.ProjectId==Model.Id);
            if (ViewBag.IsApplied == null)
            {
                <button class="btn btn-primary" id="btnApply" onclick="Apply('@Model.Id')">
                    Apply
                </button>
            }
            else
            {
                if (selectProject == null)
                {
                <button class="btn btn-primary"  onclick="Retreat('@Model.Id')">
                    Retreat
                </button>
                    }
                }

            }

    </div>
    <div class="panel-body">
        <table class="table table-responsive">
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Name)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Name)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.ProjectTools)
                </td>
                <td>
                    @Html.DisplayFor(model => model.ProjectTools)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.ProjectType)
                </td>
                <td>
                    @Html.DisplayFor(model => model.ProjectType)
                </td>
            </tr>
            <tr>
                <td style="font-weight: bold">
                    @Html.DisplayNameFor(model => model.IsApproved)
                </td>
                <td>
                    @if (Model.IsApproved == false || Model.IsApproved==null)
                                        {
                    <text>No</text>
                                        }
                                        else
                                        {
                    <text>Yes</text>
                                        }
                    @*@Html.DisplayFor(model => model.IsApproved)*@
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.ApprovalRejectionDate)
                </td>
                <td>
                    @Html.DisplayFor(model => model.ApprovalRejectionDate)
                </td>
            </tr>
            <tr>
                <td style="font-weight: bold">
                    @Html.DisplayNameFor(model => model.IsClosed)
                </td>
                <td>
                    @if (Model.IsClosed == false )
                                        {
                    <text>No</text>
                                        }
                                        else
                                        {
                    <text>Yes</text>
                                        }
                    @*@Html.DisplayFor(model => model.IsApproved)*@
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.MaxApprovedStudents)
                </td>
                <td>
                    @Html.DisplayFor(model => model.MaxApprovedStudents)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Description)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Description)
                </td>
            </tr>
        </table>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">Project Bids</div>
    <div class="panel-body">
        <table id="gridStudentChoices" data-source="@Url.Action("GetProjects", "ProjectStudentChoices", new { projectId = Model.Id })"></table>
    </div>
</div>



<div>
    <a asp-action="Index" class="btn btn-danger">Back to List</a>
</div>

ProjectManagement/Views/ProjectBid/Index.cshtml
@model IEnumerable<ProjectManagement.DataContextModels.Project>
@{
    ViewData["Title"] = "Index";
}


<script type="text/javascript">
    var grid;

    $(document).ready(function () {
        if ($('#projectType').val() != 'Bachelor') {
            $('#projectSubType').prop("disabled", "disabled");
        }


         // Load Grid using json object
        grid = $("#grid").grid({
            dataKey: "id",
            uiLibrary: "bootstrap",
            columns: [
                { field: "name", title: "Name", sortable: true, width: 40 },
                { field: "projectType", title: "Type", sortable: true, width: 40 },
                { field: "approvalSummary", title: "Approved", sortable: true, width: 20 },
                { field: "closerSummary", title: "Closed", sortable: true, width: 20 },
                { field: "maxApprovedStudents", title: "Students", sortable: true, width: 30 },
                { field: "createdBy", title: "Supervisor", sortable: true, width: 40 },
                { title: "Details", field: "Details", width: 10, type: "icon", icon: "glyphicon-circle-arrow-right", tooltip: "Details", events: { "click": Details } },

            ],
            pager: { enable: true, limit: 40, sizes: [2, 5, 10, 20, 40] }
        });

        if (grid.rows[3].value === 0) {
            grid.rows[3].value = "No";
        } else {
            grid.rows[3].value = "yes";
        }



        $('#projectType').change(function () {
            var ddlsource = "#projectType";
            var projectType = $(ddlsource).val();
            if (projectType != 'Bachelor') {
                $('#projectSubType').prop("disabled", "disabled");
            }
            else {
                $('#projectSubType').removeAttr("disabled");
            }
        });

    });




    // Details
       function Details(e) {
        var record = JSON.stringify(e.data.record);
        var items = JSON.parse(record);
        var id = items.id;
        var url = '@Url.Action("Details", "ProjectBid")' + '/' + id;
        window.location.href = url;
    }



    // Search
    function Search() {
        grid.reload(
            {
                projectName: $("#projectName").val(),
                projectType: $('#projectType').val(),
                projectSubType: $("#projectSubType").val(),
                Professor: $("#Professor").val(),
                page: 1
            });
    }


</script>
<h2>Projects</h2>

<div>
    <div>
        <table class="table" style="width:70%">
            <tr>
                <td>
                    <strong>Project Title</strong>
                </td>
                <td>
                    <input id="projectName" name="projectName" class="form-control" />
                </td>
                <td>
                    <strong>Project Type</strong>
                </td>
                <td>

                    <select id="projectType" name="projectType" class="form-control">
                        <option value="Select">Select ...</option>
                        <option value="Bachelor">Bachelor</option>
                        <option value="Master">Master</option>
                        <option value="Doctorate">Doctorate</option>
                    </select>
                </td>
                <td></td>

            </tr>
            <tr>

                <td>
                    <strong>Project SubType</strong>
                </td>
                <td>

                    <select id="projectSubType" name="projectSubType" class="form-control">
                        <option value="Select">Select ...</option>
                        <option value="IT">IT</option>
                        <option value="CS">CS</option>

                    </select>
                </td>
                <td>
                    <strong>Supervisor</strong>
                </td>
                <td>
                    <input class="form-control" id="Professor" />
                </td>

                <td>
                    <button type="button" id="btnSearch" class="btn btn-default" onclick="Search();">
                        <span class="glyphicon glyphicon-search"></span>
                        Search
                    </button>
                </td>
            </tr>
        </table>
    </div>
</div>

<hr />
<div>
  
    <table id="grid" data-source="@Url.Action("GetProjects")"></table>
</div>

ProjectManagement/Views/ProjectBid/MyProjects.cshtml
@{
    ViewData["Title"] = "My Projects";
}
<script type="text/javascript">
    var gridStudentChoices, gridStudentApproved;
    $(document).ready(function () {

         // Load Grid using json object
        gridStudentChoices = $("#gridStudentChoices").grid({
            dataKey: "id",
            uiLibrary: "bootstrap",
            columns: [
                { field: "projectName", title: "Project", sortable: true, width: 40 },
                { field: "professor", title: "Supervisor", sortable: true, width: 40 },
            

            ],
            pager: { enable: true, limit: 40, sizes: [2, 5, 10, 20, 40] }
        });

        // Load Grid using json object
        gridStudentApproved = $("#gridStudentApproved").grid({
            dataKey: "id",
            uiLibrary: "bootstrap",
            columns: [
                { field: "projectName", title: "Project", sortable: true, width: 40 },
                { field: "professor", title: "Supervisor", sortable: true, width: 40 },
               
            ],
            pager: { enable: true, limit: 5, sizes: [2, 5, 10, 20, 40] }
        });

    });

  



</script>
<h2>My Projects</h2>
<div class="panel panel-default">
    <div class="panel-heading">Project Bids</div>
    <div class="panel-body">
        <table id="gridStudentChoices" data-source="@Url.Action("GetProjects", "ProjectStudentChoices", new { studentId =  ViewBag.StudentId })"></table>
    </div>
</div>
<hr />
<div class="panel panel-default">
    <div class="panel-heading">Approved Projects</div>
    <div class="panel-body">
        <table id="gridStudentApproved" @*data-source="@Url.Action("GetProjects", "ProjectStudents", new { studentId =  ViewBag.StudentId })"*@></table>
    </div>
</div>